### ISSUE TITLE
Storage Config > 2TB bug

### ISSUE THREAD

**Issue by frogg** [0xCUB3/About-This-Hack#61]
<img width="692" alt="Screenshot 2023-10-09 at 08 01 50" src="https://github.com/0xCUB3/About-This-Hack/assets/5204169/3c4d78a5-2760-40f7-878e-4f41015ab705">

```
Directory created...
Files created...
14.0
OS Build Number:  (23A344)
RAM Type: LPDDR5

RAM Speed:
["Apple M1 Pro"]
1
loaded
Support View Initializing...
Initializing Main View...
TEST TEST /private/tmp/.ath/scr.txt
Number of Displays: 2
Has built-in display: true
Startup Disk Name Macintosh HD
Storage Type: true
Size: 2.0
Available: 401.3
%: 20065.00
Storage Data: Macintosh HD (Internal Apple)
2.0 TB (401.3 GB Available - 20065.00%)
Size: 2.0
Available: 401.3
%: 20065.00
Storage Percent: -199.65
TEST TEST /private/tmp/.ath/scr.txt
TEST TEST /private/tmp/.ath/scr.txt
2 or 3 displays found
zsh:2: command not found: Color
[1]    62649 trace trap  /Applications/About\ This\ Hack.app/Contents/MacOS/*
```

**Comment by MDNich** [comment]
Renamed to clarify cause

**Comment by MDNich** [comment]
Oh no I'm sorry there is indeed a storage issue.

**Comment by MDNich** [comment]
See if you can run this @frogg 
```
egrep "[Container|Volume] Total Space:" "/tmp/.ath/sysvolname.txt" | awk '{print $4,$5}'
```
Let me know what is printed

**Comment by MDNich** [comment]
Ok I have made a potential fix, do try this and let me know if it works for you:

https://www.mediafire.com/file/b431dfoa8mramfi/About+This+Hack.zip/file

**Comment by matxpa** [comment]
@MDNich @0xCUB3 

Try with a conversion to the same unit (GB) of size on Disk total size and Available total size
(don't copy lines below, github view didn't return editor real edited code)

Not tested (I don't have N TB SSD)

HardwareCollector.swift
...
    static func getStorageData() -> [String] {

...
    let size = run("egrep \"[Container|Volume] Total Space:\" | awk '{print $4,$5}'  | tr -d '\n'")
    let diskSizeUnit =  run("echo \"\(size)\" | awk '{print $2}' | tr -d '\n'")
        switch run("echo \"\(size)\" | awk '{print $2}' | tr -d '\n'") {
        case "GB"   : coeffMultDiskSIze = 1
        case "MB"   : coeffMultDiskSIze = 0,1
        case "TB"   : coeffMultDiskSIze = 10
        default     : coeffMultDiskSIze = 1
        }
    let sizeTrimmed = (Double(run("echo \"\(size)\" | awk '{print $1}' | tr -d '\n'"))! * coeffMultDiskSIze)

    let available = run("grep \"[Container|Volume] Free Space:\" | awk '{print $4,$5}' | tr -d '\n'")
    let availableSizeUnit =  run("echo \"\(available)\" | awk '{print $2}' | tr -d '\n'")
        switch run("echo \"\(available)\" | awk '{print $2}' | tr -d '\n'") {
        case "GB"   : coeffMultAvailableSIze = 1
        case "MB"   : coeffMultAvailableSIze = 0,1
        case "TB"   : coeffMultAvailableSIze = 10
        default     : coeffMultAvailableSIze = 1
        }
     let availableTrimmed = (Double(run("echo \"\(available)\" | awk '{print $2}' | tr -d '\n'"))! * coeffMultAvailableSIze)
...   

Regards

**Comment by MDNich** [comment]
@matxpa Have you tried with the app I have uploaded ? Thank you for the rest though.

**Comment by MDNich** [comment]
https://www.mediafire.com/file/b431dfoa8mramfi/About+This+Hack.zip/file

**Comment by MDNich** [comment]
Will keep you updated.

**Comment by matxpa** [comment]
Yes but let me set this fix in my Repo (main branch)

**Comment by MDNich** [comment]
The only thing I would change in your code is obtaining the unit - better to pull it from the first shell string to optimize time spent. 

```swift
let unit = size[size.length-2]
```

```swift
extension String {

    var length: Int {
        return count
    }

    subscript (i: Int) -> String {
        return self[i ..< i + 1]
    }

    func substring(fromIndex: Int) -> String {
        return self[min(fromIndex, length) ..< length]
    }

    func substring(toIndex: Int) -> String {
        return self[0 ..< max(0, toIndex)]
    }

    subscript (r: Range<Int>) -> String {
        let range = Range(uncheckedBounds: (lower: max(0, min(length, r.lowerBound)),
                                            upper: min(length, max(0, r.upperBound))))
        let start = index(startIndex, offsetBy: range.lowerBound)
        let end = index(start, offsetBy: range.upperBound - range.lowerBound)
        return String(self[start ..< end])
    }
}
```

**Comment by matxpa** [comment]
I've pushed this code in HardwareCollector.swift in my Repo (main branch) so get and keep what you need

**Comment by MDNich** [comment]
Merged, thank you. I also adjusted slightly the notation with the optimization I mentioned.

@frogg, if you could test the release tag I'm about to attach here, if it works we can make it as finished.

**Comment by matxpa** [comment]
Yes and the 2 last sent issues (#62 #63) seem to be same as #60 one

**Comment by MDNich** [comment]
Thanks for your help :)

**Comment by matxpa** [comment]
With your About-This-Hack-storage-test-1 built with Xcode 14.2 (Monterey) (Xcode 15.0 Ventura ou Sonoma debug can't work)

![Capture d’écran 2023-10-10 à 17 15 25](https://github.com/0xCUB3/About-This-Hack/assets/70573409/0da200bf-7305-42a8-ae22-3388f9c90237)

I'll try with forced values TB and MB (MB for the fun)

Regards

**Comment by MDNich** [comment]
Ok looks good yes ?

**Comment by MDNich** [comment]
sorry I don't have Xcode 12.5 like 0xCUB3, just Sonoma 
<img width="642" alt="Capture d’écran 2023-10-10 à 18 18 34" src="https://github.com/0xCUB3/About-This-Hack/assets/71262643/80746416-03db-44fe-902c-30e99618e6fd">

**Comment by MDNich** [comment]
That's my bad - I wrote exactly what you wrote, but the `size` and `available` already include the unit. Fixed in this push.

**Comment by MDNich** [comment]
https://www.mediafire.com/file/prqoarm95ppn0jr/About+This+Hack.zip/file @frogg

**Comment by matxpa** [comment]
With the app. above

![Capture d’écran 2023-10-10 à 17 36 05](https://github.com/0xCUB3/About-This-Hack/assets/70573409/ba8b7697-7e23-40f3-ac6e-7e879b85759f)

**Comment by matxpa** [comment]
@MDNich 

"Did you apply the first commit in my Repo (main branch) commit concerning SIP returned value when SIP is enabled" 

I apologize, yes you did, I can see it in the proj you sent.

**Comment by matxpa** [comment]
@0xCUB3  @MDNich  @frogg 

Hi all
This issue isn't fixed ?
Regards

**Comment by MDNich** [comment]
Waiting on @frogg to test before closing.

**Comment by matxpa** [comment]
Ok

**Comment by 0xCUB3** [comment]
@frogg you there?

**Comment by 0xCUB3** [comment]
closing issue because of inactivity; assuming fixed
